### ISSUE TITLE
Could not work with classes

### ISSUE THREAD

**Issue by anmsajedulalam** [hanoglu/TermiC#3]
I was testing with simple functions, which worked then, but when I tried to implement classes with it, it did not work. I installed dependencies. 

[issue](https://ibb.co/7StshRj)

**Comment by hanoglu** [comment]
You have been using termic in C mode. As you know object oriented programming is not supported in C.
Instead you can run termic++ to use C++ functionality.

**Comment by anmsajedulalam** [comment]
Okay, I got it now. Thanks. Did not notice before.
