### ISSUE TITLE
TermiC does not exit after EOF, but exits after receiving a SIGINT

### ISSUE THREAD

**Issue by veractor** [hanoglu/TermiC#4]
After receiving an EOF character (Ctrl+D) on an empty line, TermiC does not exit, and opens a new line.

Instead, sending a SIGINT (Ctrl+C) would quit TermiC in the same way I expected an EOF to do so. But SIGINT should not stop a REPL.

Ideally, I think it should behave like other REPLs such as bash, where the program would end after an EOF, which is much more intuitive (since we are using bash already!).

Great job on this nifty piece of shell script btw! I use it a lot for quick things like getting the sizeof of a non-standard type in GCC, and it's neaten up my workflow a lot by removing the need for temporary source files everywhere on my desktop :P

**Comment by hanoglu** [comment]
The new version supports both Ctrl-D and Ctrl-C combinations as in Python terminal.
